### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by dysfungi** [defrank/python_programming_task#1]
# AsyncProxy - Python Programming Task

Your task is to build an asynchronous HTTP proxy (see definition in [RFC2616](https://www.ietf.org/rfc/rfc2616.txt)) complying to the requirements specified below.

## Requirements
* [README](https://github.com/defrank/python_programming_task/blob/master/README.md)
* [rfc2616](https://www.ietf.org/rfc/rfc2616.txt)
* [x] Range requests must be supported as defined in [RFC2616](https://www.ietf.org/rfc/rfc2616.txt), but also via `range` query
parameter.
* [x] HTTP 416 error must be returned in case where both header and query parameter are
specified, but with a different value.
* [x] Program must start with a single command `docker-compose up`.
* [x] Proxy must be reachable at `http://<docker-host>:8080` .
* [x] Usage statistics must be available at `http://<docker-host>:8080/stats`
    * total bytes transferred
    * uptime
* [x] Code must run with Python 3.5+.
* [x] Code must be delivered as a link to public GitHub repository.

#### Bookmarks
* Proxy specific
    * 1.3 proxy
* Range specific
    * 3.12 Range Units
    * 10.4.17 416 Requested Range Not Satisfiable
    * 14.16 Content-Range
    * 14.35 Range
    * 19.2 Internet Media Type multipart/byteranges
* Misc
    * 5.1.2 Request-URI
    * 14.10 Connection

#### Assumptions
* **async** (in async HTTP proxy) is in regards to handling requests asynchronously.  This will be covered by the framework (e.g., Django, Tornado, BottlePy).  Assuming [gevents (greenlets)](http://bottlepy.org/docs/0.12/async.html#greenlets-to-the-rescue)'s multithreading is close enough to async
* Proxy server is transparent, not anonymous
* `range` query parameter must be lowercase, but header is handled case-insensitively
*`total_bytes_transferred` refers only to the content length of responses sent from the proxy server to the client.  Does not include headers, cookies, or request data.
* `uptime` is server uptime, not transfer time
* No gzip support for client
* No support for streaming
* /stats can return JSON formatted values

#### Frameworks
* [async Python web frameworks](https://www.slant.co/improve/topics/3173/~python-asynchronous-web-frameworks)
    * [Tornado](http://www.tornadoweb.org/en/latest/guide/intro.html)
* synchronous web frameworks
    * [BottlePy](http://bottlepy.org/docs/dev/index.html)
        * http://bottlepy.org/docs/stable/deployment.html#switching-the-server-backend
        * https://bottlepy.org/docs/dev/async.html
    * [Flask](http://flask.pocoo.org/)

### Todo
* [x] Choose async framework: [BottlePy with gevent(greenlets)](http://bottlepy.org/docs/stable/deployment.html#switching-the-server-backend)
* [x] Implement basic transparent proxy
* [x] Implement stats using SQLite to store the data
* [x] Support proxy HEAD, GET, POST, PUT, DELETE
* [x] Add support for range requests
* [x] Proxy server `uptime`
* [x] `total_bytes_transferred` of just response content length

### Future
* Handle response content as a file or buffer to save memory
* Use Python 3.5 `async` and `await`...
* Support gzip encoding responses to client
* Support streaming
